import{a as P,S,i as c}from"./assets/vendor-CucEYOFD.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=a(r);fetch(r.href,o)}})();async function u(t,e=1){const a=new URLSearchParams({key:"38288513-b7843bc63d8f48176142cf2e3",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15});return await(await P.get("https://pixabay.com/api/",{params:a})).data}const g=document.querySelector(".gallery"),h=document.querySelector(".loader"),f=document.querySelector(".load-more"),b=new S(".gallery a",{captionsData:"alt",captionDelay:250});function v({webformatURL:t,largeImageURL:e,tags:a,likes:s,views:r,comments:o,downloads:i}){return`
    <li class="gallery-item">
      <a href="${e}" data-lightbox="gallery">
        <img src="${t}" alt="${a}" />
      </a>
      <div class="details">
        <p><strong>Likes:</strong> ${s}</p>
        <p><strong>Views:</strong> ${r}</p>
        <p><strong>Comments:</strong> ${o}</p>
        <p><strong>Downloads:</strong> ${i}</p>
      </div>
    </li>
  `}function m(t){const e=t.map(v).join("");g.insertAdjacentHTML("beforeend",e),b.refresh()}function q(){g.innerHTML=""}function p(){h.classList.remove("hidden")}function y(){h.classList.add("hidden")}function M(){f.classList.remove("hidden")}function d(){f.classList.add("hidden")}const L=document.querySelector(".form"),R=document.querySelector(".load-more");let n=1,l="",H;L.addEventListener("submit",I);R.addEventListener("click",$);async function I(t){if(t.preventDefault(),l=t.target.elements["search-text"].value.trim(),!l){c.info({title:"Info",message:"Please enter a search query.",position:"topRight"});return}n=1,q(),d(),p();try{const e=await u(l,n);if(e.hits.length===0){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(e.hits),console.log(e.totalHits),w(e.totalHits,n),H=Math.ceil(e.totalHits/15)}catch{c.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y()}L.reset()}async function $(){n+=1,d(),p();try{const t=await u(l,n);m(t.hits),w(t.totalHits,n),x()}catch{c.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y()}}function w(t,e){const a=Math.ceil(t/15);e>=a?(d(),c.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):M()}function x(){const t=document.querySelector(".gallery-item");if(!t)return;const e=t.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
